/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Aspect: typeof import('./src/components/analysis/Aspect.vue')['default']
    Buffer: typeof import('./src/components/analysis/Buffer.vue')['default']
    Chart: typeof import('./src/components/Chart.vue')['default']
    ColorMap: typeof import('./src/components/ColorMap.vue')['default']
    Contour: typeof import('./src/components/analysis/Contour.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Excavation: typeof import('./src/components/analysis/Excavation.vue')['default']
    Flood: typeof import('./src/components/analysis/Flood.vue')['default']
    Fly: typeof import('./src/components/general/Fly.vue')['default']
    Heatmap: typeof import('./src/components/analysis/Heatmap.vue')['default']
    HeightRestriction: typeof import('./src/components/analysis/HeightRestriction.vue')['default']
    Isosurface: typeof import('./src/components/analysis/Isosurface.vue')['default']
    Light: typeof import('./src/components/general/effect/Light.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    Measure: typeof import('./src/components/general/Measure.vue')['default']
    Model: typeof import('./src/components/Model.vue')['default']
    Particle: typeof import('./src/components/general/effect/Particle.vue')['default']
    Planish: typeof import('./src/components/analysis/Planish.vue')['default']
    Profile: typeof import('./src/components/analysis/Profile.vue')['default']
    Rainy: typeof import('./src/components/general/weather/Rainy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shadow: typeof import('./src/components/analysis/Shadow.vue')['default']
    Sight: typeof import('./src/components/analysis/Sight.vue')['default']
    Skyline: typeof import('./src/components/analysis/Skyline.vue')['default']
    Slope: typeof import('./src/components/analysis/Slope.vue')['default']
    Snowy: typeof import('./src/components/general/weather/Snowy.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Template: typeof import('./src/components/template.vue')['default']
    Viewshed: typeof import('./src/components/analysis/Viewshed.vue')['default']
    Weather: typeof import('./src/components/general/weather/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
